### ISSUE TITLE
Generate docs with go generator

### ISSUE THREAD

**Issue by displague** [equinix/terraform-provider-equinix#201]
It is now possible to generate provider docs using the https://www.terraform.io/docs/registry/providers/docs.html#generating-documentation generator and fields embedded in the provider.

Can we generate all of our documentation identically in this way?

The generator is noted to have some weakness handling deep structures.

Some example repositories using this method:
* https://registry.terraform.io/providers/hashicorp/boundary/latest/docs
* https://registry.terraform.io/providers/paultyng/unifi/latest/docs
* https://registry.terraform.io/providers/paultyng/sql/latest/docs

**Comment by ocobleseqx** [comment]
The draft pull request https://github.com/equinix/terraform-provider-metal/pull/15 created at equinix/terraform-provider-metal has been closed without resolution due to the complexity of migrating that work to this repository. Any related work must be recreated. Relevant information from the conversation is linked below:

_https://github.com/equinix/terraform-provider-metal/pull/15#issuecomment-750300896_
> Have a look at this thread, https://github.com/tinkerbell/terraform-provider-tinkerbell/pull/20#discussion_r542100422 and this commit https://github.com/tinkerbell/terraform-provider-tinkerbell/commit/1d2377da4208ffc773fe6738b3ff2d08c3c9a317.
>
> I think this provides a cleaner approach to introducing this bit of tooling without adding dozens of new requirements.

**Comment by ctreatma** [comment]
The provider will likely need to adopt documentation generation in a major version release, because we cannot generate docs in the current structure where files are prefix with `equinix_`: (https://github.com/hashicorp/terraform-plugin-docs/issues/347).  Our current file naming convention does not align with [the standards proposed by Hashicorp and implemented in the generator](https://developer.hashicorp.com/terraform/registry/providers/docs#navigation-hierarchy).  

Rather than fork the generator or do extra workarounds to rename files after generation, we should align with the standards that are implemented by the generator and that are used by other providers; that means breaking existing docs pages because there's no way to redirect those old URLs.
