### ISSUE TITLE
Network Edge: awsConnectionId attribute is not available

### ISSUE THREAD

**Issue by abudilov** [equinix/terraform-provider-equinix#22]
### Affected resources
ecx_l2_connection

### Output

```
module.aws.aws_dx_private_virtual_interface.vif-2: Creating...
module.aws.aws_dx_private_virtual_interface.vif-1: Creating...

Error: error creating Direct Connect private virtual interface: DirectConnectClientException: ConnectionID 57ff76d2-a875-464a-b5c7-afc03c7278d7 has an invalid format.



Error: error creating Direct Connect private virtual interface: DirectConnectClientException: ConnectionID b6fc1012-888f-4888-bc92-388c03a138d0 has an invalid format
```
### Enhancement request

When creating an AWS Virtual Interface within the Direct Connect service, a "Connection ID" attribute must be used. In the absence of AWS Data Source for 'aws_dx_connection' resource, there's no way to fetch this attribute from AWS.

Equinix Terraform provider allows creating an "equinix_ecx_l2_connection" resource and relies on ECX API to create the Direct Connect connection. ECX API L2 connection object includes actionDetails list that includes the AWS connection_id:
```
"actionDetails": [
        {
            "actionType": "EQUINIX_EXECUTE_ACTION",
            "operationId": "CONFIRM_CONNECTION",
            "actionMessage": "Please provide the following credentials so that we can confirm the connection on your behalf. You also have the option to do this operation on AWS Console",
            "actionRequiredData": [
                {
                    "key": "accessKey",
                    "label": "Amazon Access Key",
                    "value": "",
                    "editable": true,
                    "validationPattern": "{RegexForString50chars}"
                },
                {
                    "key": "secretKey",
                    "label": "Amazon Secret Key",
                    "value": "",
                    "editable": true,
                    "validationPattern": "{RegexForString24chars}"
                },
                {
                    "key": "awsConnectionId",
                    "label": "AWS Hosted Connection Id",
                    "value": "dxcon-fg8fakqw",
                    "editable": false,
                    "validationPattern": ""
                }
            ]
        }
    ],
```
#### Requesting terraform provider to expose this API attribute

**Comment by mikouaj** [comment]
@abudilov my proposal is to add `aws_connection_id` attribute to `equinix_ecx_l2_connection_accepter` resource output.

Example:
```
resource "equinix_ecx_l2_connection_accepter" "aws-dc" {
  connection_id = equinix_ecx_l2_connection.aws-dc.id
  access_key    = var.aws_access_key
  secret_key    = var.aws_secret_key
}

resource "aws_dx_private_virtual_interface" "foo" {
  connection_id = equinix_ecx_l2_connection_accepter.aws-dc.aws_connection_id
  name           = "vif-foo"
  vlan           = 4094
  address_family = "ipv4"
  bgp_asn        = 65352
}
```

Rationale of adding it to *accepter* resource rather than to *connection* resource itself is that:
* ECX Fabric API response for `GET /ecx/v3/l2/buyer/connections` provides `actionDetails` for **AWS connections only**
* in order use `aws_connection_id` in virtual interface, connection has to be accepted anyway - that implies usage of accepter anyway
* `equinix_ecx_l2_connection_accepter` was intended to cover use case that is missing in AWS Provider (approving hosted connection). It is similar situation to lack of hosted connections data source in AWS provider, that could leverage `DescribeConnections` API to get and filter hosted conns from given partner

**Comment by abudilov** [comment]
This is perfect @mikouaj. Thank you.
