### ISSUE TITLE
Network Edge Provisioning - Internal Server Error when using unavailable SW version

### ISSUE THREAD

**Issue by abudilovskiy** [equinix/terraform-provider-equinix#239]
### Problem
The provisioning of a Network Edge instance fails with a generic error when using the software version that is not available via the Portal. 
```
terraform apply -auto-approve                                                                                 
data.equinix_network_account.metro: Refreshing state... [id=SV-equinix]
equinix_network_device.network-edge: Creating...

Error: Equinix REST API error: Message: "Internal Server Error", HTTPCode: 500, ApplicationErrors: [Code: "IC-NE-IF-008", Property: "", Message: "", AdditionalInfo: ""]

  on main.tf line 13, in resource "equinix_network_device" "network-edge":
  13: resource "equinix_network_device" "network-edge" {
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version
Terraform v0.13.6
+ provider registry.terraform.io/equinix/equinix v1.8.0

### Affected Resource(s)

* equinix_network_device

### Terraform Configuration Files

```tf
provider "equinix" {
  request_timeout = 60
  client_id = "xxxx"
  client_secret = "xxxx"
}

data "equinix_network_account" "metro" {
  metro_code = "SV"
  status     = "Active"
  name       = "equinix"
}

resource "equinix_network_device" "network-edge" {
  name               = "test-nre"
  throughput         = 500
  throughput_unit    = "Mbps"
  type_code          = "CSR1000V"
  metro_code         = "SV"
  package_code       = "SEC"
  notifications      = ["xxx"]
  hostname           = "test-nre"
  term_length        = 1
  account_number     = data.equinix_network_account.metro.number
  version            = "16.09.05"
  core_count         = 2
}
```

### Debug Output
https://gist.github.com/abudilovskiy/1fba260800bd6f821f262040e84f9d6f

### Expected Behavior

The provider should validate the available versions and offer the options similar to how it does for other attributes e.g. term length

### Actual Behavior

Generic error is thrown with no indication of what went wrong

### Steps to Reproduce

1. `terraform apply`

**Comment by displague** [comment]
@rling-equinix I believe you had some insight into which parameters may have been invalid in this resource definition. IIRC, it was based on the version of the device?

**Comment by rling-equinix** [comment]
Hi @abudilovskiy, 

The issue is caused by software version, an informative error message will be needed for such validation. I will work with our API team to enhance those error messages.

For your suggestion under the expected behavior section, software versions are vendor based, we cannot enforce similar static validation from the terraform side like what we did for the term length field.

From terraform, you can get the latest version for each package from our existing **equinix_network_device_software** data source. 
Here is the example:
```terraform
data "equinix_network_device_software" "csr1000V" {
  device_type = "CSR1000V"
  packages = ["IPBASE"]
  most_recent = true
}
```
Under the same data source documentation page, you can find this [Network Edge Vendors and Devices](https://docs.equinix.com/en-us/Content/Interconnection/NE/user-guide/NE-vendors-devices.htm) page. It provides all different combinations of available versions for each vendor along with their release notes.

Thanks for pointing out this issue and making our product better!
