### ISSUE TITLE
OCI sellerprofiles don't have speed information

### ISSUE THREAD

**Issue by javiernegro** [equinix/terraform-provider-equinix#248]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

Terraform v1.2.8
on windows_amd64
+ provider registry.terraform.io/equinix/equinix v1.5.0
+ provider registry.terraform.io/hashicorp/oci v4.91.0
+ provider registry.terraform.io/oracle/oci v4.91.0

### Affected Resource(s)

equinix_ecx_l2_sellerprofiles
equinix_ecx_l2_sellerprofile

### Terraform Configuration Files

```tf
data "equinix_ecx_l2_sellerprofiles" "all" {
  organization_global_name = "ORACLE"
  metro_codes              = ["FR"]
  speed_bands              = ["1GB"]
}
```

### Expected Behavior

It should list the available sellerprofiles

### Actual Behavior

We have to remove the 'speed_bands' constraint. Looking at the data object, the list speed_band is empty for OCI profiles. Using the API rest it shows speeds: 
curl --request  GET --url 'https://api.equinix.com/ecx/v3/l2/serviceprofiles/services?metroCode=FR&pageNumber=0&pageSize=2000' --header 'accept: application/json' --header 'content-type: application/json' --header 'authorization: Bearer XXXXX'

### Steps to Reproduce

1. `terraform apply`

**Comment by ocobleseqx** [comment]
Hi Javier, the Equinix Fabric API request you mentioned, which is consumed by the terraform provider, does not return the available speed bands for the OCI service profile. This is due to the way the Equinix Fabric API internally consumes the OCI API. If you create the connection using the UI console, you will notice that the available bandwidth shapes only appear after the authorization key (virtual circuit OCID) is validated.

We will use this issue to update the documentation and warn that the speeds are not available for some providers and may return empty results.

Alternatively, in case you need that information, you can get that it using the OCI terraform provider:

```
data "oci_core_fast_connect_provider_services" "test_fast_connect_provider_services" {
    compartment_id = var.compartment_id
}

locals {
    fc_equinix_id = [for p in data.oci_core_fast_connect_provider_services.test_fast_connect_provider_services.fast_connect_provider_services : p.id if p.provider_name == "Equinix"][0]
}

data "oci_core_virtual_circuit_bandwidth_shapes" "test_virtual_circuit_bandwidth_shapes" {
    provider_service_id = local.fc_equinix_id
}

output "fc_equinix_speed_bands" {
  value = data.oci_core_virtual_circuit_bandwidth_shapes.test_virtual_circuit_bandwidth_shapes
}
```

**Comment by javiernegro** [comment]
Understood, that's a pity. Thanks for the response!
