### ISSUE TITLE
Invalid new value for seller_region

### ISSUE THREAD

**Issue by mxdlx** [equinix/terraform-provider-equinix#35]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

0.13.5 (using terraform cloud)

### Affected Resource(s)

* equinix_ecx_l2_connection

### Terraform Configuration Files

```tf
resource "equinix_ecx_l2_connection" "XXXXX" {
  name              = "XXXX"
  profile_uuid      = data.equinix_ecx_l2_sellerprofile.test_profile.uuid
  speed             = 1
  speed_unit        = "GB"
  notifications     = ["ops@example.com"]
  port_uuid         = data.equinix_ecx_port.test_port.uuid
  vlan_stag         = 300
  seller_region     = google_compute_interconnect_attachment.test_attach.region
  #seller_metro_code = var.gcp_metro_code
  authorization_key = google_compute_interconnect_attachment.test_attach.pairing_key
}
```

### Debug Output

```
When expanding the plan for equinix_ecx_l2_connection.XXXXX
to include new values learned so far during apply, provider
"registry.terraform.io/equinix/equinix" produced an invalid new value for
.seller_region: was cty.StringVal("us-central1"), but now
cty.StringVal("https://www.googleapis.com/compute/v1/projects/project-x/regions/us-central1").
```

### Expected Behavior

The L2 connection should have been created.

### Actual Behavior

The example for GCP in this repository uses `google_compute_interconnect_attachment.test-1.region` which gets a URI value for the region. In my run, it seems it only needs the region name string.

### Steps to Reproduce

1. `terraform apply`

**Comment by mikouaj** [comment]
@mxdlx that is expected behavior, because Google has defined available regions in Equinix Fabric using region name strings only (not full URLs).

In general, values of `seller_region` argument in `equinix_ecx_l2_connection` resource have to correspond to regions from `equinix_ecx_l2_sellerprofile` data source.

You can use `data.equinix_ecx_l2_sellerprofile.<resource_name>.metro` attribute to get metros and regions for a seller profile :
1. First select desired GCP's metro location (i.e. using metro of your port in case of local connectivity)
2. Then get available regions

i.e.:
```
locals {
  ecx_gcp_metros = tolist(data.equinix_ecx_l2_sellerprofile.test_profile.metro)
  ecx_gcp_mymetro_regions = element(
    local.ecx_gcp_metros,
    index(
      local.ecx_gcp_metros.*.code,
      data.equinix_ecx_port.test_port.metro_code
    )
  ).regions
} 
```
