### ISSUE TITLE
[Bug]: Assets for v1.25.0 Release Not Found

### ISSUE THREAD

**Issue by ErikJiang** [equinix/terraform-provider-equinix#523]
### Terraform Version

v1.3.7

### Equinix Provider Version

version="1.25.0"

### Debug Output

There seem to be some issues with the release of version 1.25.0 of the equinix/equinix package. The build output assets are clearly missing, and an error occurs when executing terraform init, indicating a 404 error.

<img width="908" alt="image" src="https://github.com/equinix/terraform-provider-equinix/assets/10629406/7e6b2410-53c6-4627-a591-e8dfa593ecdf">

![image](https://github.com/equinix/terraform-provider-equinix/assets/10629406/d5691bca-bb24-42d9-af7e-06f5441304d8)

### Expected Behavior

The expected behavior is to be able to successfully retrieve the provider for version v1.25.0.

### Actual Behavior

The assets related to version v1.25.0 cannot be found.

### Steps to Reproduce

``` sh
$ cat test/provider.tf
terraform {
  required_providers {
    equinix = {
      source = "equinix/equinix"
      version = "1.25.0"
    }
  }
}

provider "equinix" {
  # Configuration options
}

$ terraform -chdir="test" init
```

**Comment by ctreatma** [comment]
The release artifacts for v1.25.0 were accidentally deleted after release.  We have released v1.25.1, which is identical to v1.25.0 but has a different version number because [republishing provider release artifacts after they have been deleted or corrupted causes SHA mismatch errors](https://developer.hashicorp.com/terraform/registry/providers/publishing).
