### ISSUE TITLE
[Bug]: datasource equinix_metal_project doesn't work searching by name

### ISSUE THREAD

**Issue by ocobles** [equinix/terraform-provider-equinix#549]
### Terraform Version

Terraform v1.7.1 on darwin_amd64

### Equinix Provider Version

provider registry.terraform.io/equinix/equinix v1.26.0

### Effected Terraform Resources

datasource equinix_metal_project

### Expected Behavior

find the existing project

### Actual Behavior

```
2024-01-31T17:03:19.450+0100 [TRACE] terraform.contextPlugins: Schema for provider "registry.terraform.io/equinix/equinix" is in the global cache
╷
│ Error: no project found with name ocm-tf-test
│ 
│   with data.equinix_metal_project.foobar,
│   on main.tf line 14, in data "equinix_metal_project" "foobar":
│   14: data "equinix_metal_project" "foobar" {
│ 
```
However I can retrieve that project by id

```
# Get Project 
data "equinix_metal_project" "foobar" {
  # name = "ocm-tf-test"
  project_id = "b3b111d4-a313-4132-a824-XXXX"
}
```

```
2024-01-31T17:09:06.422+0100 [TRACE] Completed graph transform *terraform.TransitiveReductionTransformer (no changes)

Changes to Outputs:
  + name = "ocm-tf-test"

```

### Steps to Reproduce

```
terraform {
  required_providers {
    equinix = {
      source = "equinix/equinix"
      # version = "9.0.0"
    }
  }
}

# Credentials for all Equinix resources
provider "equinix" {}

# Get Project by name
data "equinix_metal_project" "foobar" {
  name = "ocm-tf-test"
}
```

`terraform apply`

**Comment by ctreatma** [comment]
Looks like this was broken in the SDK conversion; the data source isn't using `ExecuteWithPagination` for the name search: https://github.com/equinix/terraform-provider-equinix/blob/main/equinix/data_source_metal_project.go#L124

Side note, it looks like searching projects by name is available in the API, so it might be good to adopt that instead of client-side filtering: https://github.com/equinix/equinix-sdk-go/blob/main/services/metalv1/api_projects.go#L1531-L1535

In any case we should add an acceptance test for using the project data source with a name filter.
