### ISSUE TITLE
[Bug]: terraform plan fails on data.equinix_fabric_ports with parsing time error

### ISSUE THREAD

**Issue by davidaf123** [equinix/terraform-provider-equinix#803]
### Terraform Version

1.8.1

### Equinix Provider Version

2.9.0

### Effected Terraform Resources

data.equinix_fabric_ports

we are in the process of updating to 2.9 due to the previous equinix_fabric_ports bug that was recently introduced.

### Terraform Config Files

data "equinix_fabric_ports" "primary" {
  count = var.fabric_port_name != "" ? 1 : 0

  filters {
    name = var.fabric_port_name
  }
}

### Debug Output

error: parsing time "-0001-12-30T00:00:00Z" as "2006-01-02T15:04:05Z07:00": cannot parse "-0001-12-30T00:00:00Z" as "2006"

Response contains error diagnostic: tf_provider_addr=registry.terraform.io/equinix/equinix tf_rpc=ReadDataSource @module=sdk.proto diagnostic_severity=ERROR tf_data_source_type=equinix_fabric_ports tf_proto_version=5.6 tf_req_id=8e0bbd95-e0e3-fcde-8f18-3bf73c85712d @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/diag/diagnostics.go:58 diagnostic_detail="" diagnostic_summary="parsing time \"-0001-12-30T00:00:00Z\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"-0001-12-30T00:00:00Z\" as \"2006\"" timestamp=2024-10-22T16:41:41.447Z

2024-10-22T16:41:41.447Z [DEBUG] provider.terraform-provider-equinix_v2.9.0:    "changeLog": {
2024-10-22T16:41:41.447Z [DEBUG] provider.terraform-provider-equinix_v2.9.0:     "createdDateTime": "2019-07-03T20:42:12Z",
2024-10-22T16:41:41.447Z [DEBUG] provider.terraform-provider-equinix_v2.9.0:     "updatedDateTime": "-0001-12-30T00:00:00Z"
2024-10-22T16:41:41.447Z [DEBUG] provider.terraform-provider-equinix_v2.9.0:    },

### Expected Behavior

Plan should run w/o error

### Actual Behavior

Plan fails.

### Steps to Reproduce

Only certain circuits appear to have the issue with the negative date value.

**Comment by thogarty** [comment]
Hi @davidaf123 , looks like there's an error in the API response updatedDateTime formatting for the port you're trying to retrieve data for.

The ports that have the issue will need to be fixed by the Ports team to resolve the issue. We'll need to collect more information about them from you so that we can pass it on to Fabric Ports.

I'll get you a list of the details needed as well as the best place to send it so that you're account information stays secure.

**Comment by davidaf123** [comment]
+ my work email since i couldn’t open under that git login

thank you

Sent from my phone
951.498.8955

On Oct 22, 2024, at 10:44 AM, thogarty ***@***.***> wrote:

﻿
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi @davidaf123<https://github.com/davidaf123> , looks like there's an error in the API response updatedDateTime formatting for the port you're trying to retrieve data for.

The ports that have the issue will need to be fixed by the Ports team to resolve the issue. We'll need to collect more information about them from you so that we can pass it on to Fabric Ports.

I'll get you a list of the details needed as well as the best place to send it so that you're account information stays secure.

**Comment by davidaf123** [comment]
+ Shahram, who opened case 20609321

**Comment by thogarty** [comment]
Hi @davidaf123 , best channels for getting this resolved are through creating an Equinix Support ticket because this is an API layer issue.

Fastest method for creating Equinix Support Ticket is through the Equinix Portal: https://portal.equinix.com/support
Choose the option at the bottom for `Other (...)` -> `API Support` and include the details for your account, projectId, and Ports that you are receiving the issue for. You can also include my Equinix username of thogarty so that the support team knows you've contacted me and I can route it to the right team quickly.

If you're unable to login to the portal, you can send an email to [support@equinix.com](mailto:support@equinix.com) with the same details saying that there is an API issue with the Fabric Ports API not returning correct date/time format for updatedDateTime on Ports API Responses. You can CC me on that email as well (thogarty@equinix.com) to expedite the process as well. Email method will be slightly slower to get the ticket into the right queue though.

**Comment by davidaf123** [comment]
We have opened 20609321. will update w/ additional info.

**Comment by thogarty** [comment]
@davidaf123 , marking this resolved based on Ports API Update.
